In [1]:
import numpy 

In [2]:
!pip install numpy

In [5]:
import numpy as np

In [16]:
_0_dim = np.array(10)
_1_dim = np.array([1,2,3,4])
_2_dim = np.array(
    [
        [1,2,3],
        [4,5,6]
    ]
)
_3_dim = np.array(
    [
        [[1,2,3],[4,5,6]],
        [[7,8,9],[1,1,1]],
        [[0,1,2],[1,2,0]],
        [[10,1,3],[10,5,6]]
    ]
)

In [17]:
# melihat ukuran array
print(_0_dim.shape)
print(_1_dim.shape)
print(_2_dim.shape)
print(_3_dim.shape)

()
(4,)
(2, 3)
(4, 2, 3)


In [21]:
# mengambil nilai dari array
print(_1_dim[1])
print(_1_dim[:3])

2
[1 2 3]


In [23]:
_2_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
#mengambil nilai 2 [baris, kolom]
_2_dim[0,1]

2

In [26]:
_2_dim[1,2]

6

In [27]:
_2_dim[:, 2]

array([3, 6])

In [33]:
random_int_matrix = np.random.randint(1, 20, size=(3,5))
random_int_matrix

array([[14, 15,  1,  5, 17],
       [ 3,  8,  1, 10, 10],
       [ 8,  7,  4, 18,  5]])

In [42]:
# [8,1,10]
# [7,4,18]
random_int_matrix[1:, 1:4]

array([[ 8,  1, 10],
       [ 7,  4, 18]])

In [43]:
random_int_matrix = np.random.randint(1, 20, size=(4,5))
random_int_matrix

array([[ 6, 13,  2,  9, 14],
       [ 7,  6,  5, 14,  1],
       [ 4,  4,  4,  2, 16],
       [11, 12, 16, 17,  3]])

In [44]:
random_int_matrix.shape

(4, 5)

In [45]:
# [5,14]
# [4,2]
# [16,17]
random_int_matrix[1:,2:4]

array([[ 5, 14],
       [ 4,  2],
       [16, 17]])

In [52]:
np.array(['laki-laki', 'perempuan', 'laki-laki', 8, 10.1])

array(['laki-laki', 'perempuan', 'laki-laki', '8', '10.1'], dtype='<U32')

In [56]:
#melihat tipe
_0_dim.dtype, _1_dim.dtype, _2_dim.dtype

(dtype('int32'), dtype('int32'), dtype('int32'))

In [58]:
_2_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
#mengubah tipe data
_2_dim_float = _2_dim.astype(float)
print(_2_dim_float)
print(_2_dim_float.dtype)

[[1. 2. 3.]
 [4. 5. 6.]]
float64


In [63]:
_2_dim_float32 = _2_dim.astype('float32')
_2_dim_float32.dtype

dtype('float32')

In [64]:
_2_dim.astype(str)

array([['1', '2', '3'],
       ['4', '5', '6']], dtype='<U11')

### Operasi Matrix

In [67]:
zero_matrix = np.zeros((2,3))
zero_matrix

array([[0., 0., 0.],
       [0., 0., 0.]])

In [69]:
ones_matrix = np.ones((3,5))
ones_matrix

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [74]:
identity_matrix = np.identity(4)
identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [87]:
m_int = np.random.randint(1, high=100, size=(3,2))
m_int

array([[27, 95],
       [50,  4],
       [80, 11]])

In [102]:
m_float = np.random.rand(3, 2)
m_float

array([[0.99093178, 0.94777769],
       [0.46889298, 0.27051536],
       [0.9504099 , 0.09986965]])

In [103]:
#penjumlahan matrix
m_int + m_float

array([[27.99093178, 95.94777769],
       [50.46889298,  4.27051536],
       [80.9504099 , 11.09986965]])

In [104]:
m_int - m_float

array([[26.00906822, 94.05222231],
       [49.53110702,  3.72948464],
       [79.0495901 , 10.90013035]])

In [105]:
m_int / m_float

array([[ 27.24708262, 100.23447563],
       [106.63414181,  14.78659124],
       [ 84.17420714, 110.14357262]])

In [106]:
m_int * m_float

array([[26.75515798, 90.03888077],
       [23.44464875,  1.08206143],
       [76.0327922 ,  1.09856615]])

In [120]:
a = np.random.randint(1, 30, size=(10,30))
b = np.random.randint(1, 30, size=(30,299))

In [122]:
c = np.dot(a,b)
c.shape

(10, 299)

In [123]:
a.mean()

14.896666666666667

In [126]:
np.median(a)

15.0

In [127]:
np.mean(a)

14.896666666666667

In [132]:
m_int, m_int.shape

(array([[27, 95],
        [50,  4],
        [80, 11]]),
 (3, 2))

In [133]:
m_int.reshape(-1)

array([27, 95, 50,  4, 80, 11])

In [134]:
m_int.reshape(2,3)

array([[27, 95, 50],
       [ 4, 80, 11]])

In [138]:
a = np.random.rand(5,6)

In [140]:
a.reshape(3,-1).shape

(3, 10)

In [141]:
a.reshape(-1,3).shape

(10, 3)

In [142]:
a.reshape(-1,-1).shape

ValueError: can only specify one unknown dimension

In [143]:
m_int

array([[27, 95],
       [50,  4],
       [80, 11]])

In [144]:
np.sum(m_int)

267

In [146]:
m_int.sum()

267

In [148]:
np.sum(m_int, axis=0) #menjumlahkan per kolom

array([157, 110])

In [151]:
np.mean(m_int, axis=0) #rata per kolom

array([52.33333333, 36.66666667])

In [149]:
np.sum(m_int, axis=1) #menjumlahkan per baris

array([122,  54,  91])

In [152]:
np.mean(m_int, axis=1) #rata-rata per baris

array([61. , 27. , 45.5])

In [150]:
np.sum(m_int, axis=2) #menjumlahkan per baris

AxisError: axis 2 is out of bounds for array of dimension 2

## Pandas

In [153]:
import pandas as pd

In [154]:
# !pip install pandas

In [162]:
#membuat data frame dari dictionary (key : string/int, values: [list])
_dict = {
    'kolom_1': [1,2,3,4],
    'kolom_2': ['a', 'b', 'c', 'd']
}
df = pd.DataFrame(
    _dict
)
df

kolom_1 kolom_2
0        1       a
1        2       b
2        3       c
3        4       d

In [163]:
df.shape

(4, 2)

In [166]:
# membuat data frame dari numpy/list of list
_numpy = np.array([
    [1, 'a'],
    [2, 'b'],
    [3, 'c'],
    [4, 'd']
])
df = pd.DataFrame(
    _numpy,
    columns = ['kolom_1', 'kolom_2'],
)
df

kolom_1 kolom_2
0       1       a
1       2       b
2       3       c
3       4       d

In [167]:
df.columns = ['kolom_1_diubah', 'kolom_2_diubah']

In [168]:
df

kolom_1_diubah kolom_2_diubah
0              1              a
1              2              b
2              3              c
3              4              d

In [169]:
df.index = [1,2,3,4]

In [170]:
df

kolom_1_diubah kolom_2_diubah
1              1              a
2              2              b
3              3              c
4              4              d

In [173]:
df = pd.DataFrame(
    _numpy,
    columns = ['kolom_1', 'kolom_2'],
    index = range(100, 104)
)
df

kolom_1 kolom_2
100       1       a
101       2       b
102       3       c
103       4       d

In [176]:
# membuat data frame dari list of dictionary
_list_of_dict = [
    {'kolom_1': 1, 'kolom_2': 'a'},
    {'kolom_1': 2, 'kolom_2': 'b'},
    {'kolom_1': 3, 'kolom_2': 'c'},
    {'kolom_2': 'd'}
]
pd.DataFrame(_list_of_dict)

kolom_1 kolom_2
0      1.0       a
1      2.0       b
2      3.0       c
3      NaN       d

In [178]:
#load csv file to dataframe
df = pd.read_csv('creditapproval.xls - DT_NasabahKredit.csv')

In [180]:
df.to_csv('temp_csv.csv')

### Melihat tipe data

In [182]:
df.dtypes

nama_nasabah               object
jenis_kelamin              object
umur                      float64
jml_pinjaman              float64
jkw                         int64
jml_angsuran_per_bulan    float64
type_pinjaman               int64
jenis_pinjaman              int64
bi_sektor_ekonomi         float64
col                         int64
bi_golongan_debitur         int64
bi_gol_penjamin             int64
saldo_nominatif           float64
tunggakan_pokok           float64
tunggakan_bunga           float64
status kredit              object
dtype: object

In [187]:
#jumlah missing values
df.isna().sum()

nama_nasabah              0
jenis_kelamin             0
umur                      1
jml_pinjaman              0
jkw                       0
jml_angsuran_per_bulan    0
type_pinjaman             0
jenis_pinjaman            0
bi_sektor_ekonomi         1
col                       0
bi_golongan_debitur       0
bi_gol_penjamin           0
saldo_nominatif           0
tunggakan_pokok           0
tunggakan_bunga           0
status kredit             0
dtype: int64

In [183]:
#mengubah tipe data

In [185]:
df['umur'].dtype

dtype('float64')

In [188]:
df['umur'].dropna().astype(int)

0      40
1      31
2      37
3       2
4      34
       ..
761    38
762    36
763    28
764    31
765    36
Name: umur, Length: 765, dtype: int32

In [189]:
df['umur'].dropna().astype(str)

0      40.0
1      31.0
2      37.0
3       2.0
4      34.0
       ... 
761    38.0
762    36.0
763    28.0
764    31.0
765    36.0
Name: umur, Length: 765, dtype: object

In [190]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 766 entries, 0 to 765
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   nama_nasabah            766 non-null    object 
 1   jenis_kelamin           766 non-null    object 
 2   umur                    765 non-null    float64
 3   jml_pinjaman            766 non-null    float64
 4   jkw                     766 non-null    int64  
 5   jml_angsuran_per_bulan  766 non-null    float64
 6   type_pinjaman           766 non-null    int64  
 7   jenis_pinjaman          766 non-null    int64  
 8   bi_sektor_ekonomi       765 non-null    float64
 9   col                     766 non-null    int64  
 10  bi_golongan_debitur     766 non-null    int64  
 11  bi_gol_penjamin         766 non-null    int64  
 12  saldo_nominatif         766 non-null    float64
 13  tunggakan_pokok         766 non-null    float64
 14  tunggakan_bunga         766 non-null    fl

In [191]:
df.values

array([['x1', 'P', 40.0, ..., 345000.0, 0.0, 'MACET'],
       ['x2', 'L', 31.0, ..., 111428.0, 0.0, 'MACET'],
       ['x3', 'L', 37.0, ..., 216642.0, 0.0, 'MACET'],
       ...,
       ['x764', 'L', 28.0, ..., 600000.0, 180000.0, 'MACET'],
       ['x765', 'P', 31.0, ..., 1312500.0, 78750.0, 'MACET'],
       ['x766', 'P', 36.0, ..., 1000000.0, 100000.0, 'MACET']],
      dtype=object)

In [194]:
#mengurutkan berdasarkan umur
df.sort_values(by='umur', ascending=False)

nama_nasabah jenis_kelamin    umur  jml_pinjaman  jkw  \
423         x424             L  1043.0     686667.34    3   
571         x572             L    80.0     940000.00   47   
526         x527             P    76.0    2000000.00    6   
413         x414             L    68.0     769167.00   12   
67           x68             L    67.0     875000.00   17   
..           ...           ...     ...           ...  ...   
560         x561             L   -48.0     330000.00    8   
361         x362             P   -48.0     500000.00    8   
525         x526             L   -49.0    1500000.00    5   
622         x623             L -7162.0     750000.00    8   
723         x724             L     NaN     632728.00   11   

     jml_angsuran_per_bulan  type_pinjaman  jenis_pinjaman  bi_sektor_ekonomi  \
423                62222.68            100             301             6000.0   
571                20000.00            100             305             6000.0   
526               393333.35            100             301             6000.0   
413                70347.25            100             301             6000.0   
67                 54529.78            100             301             6000.0   
..                      ...            ...             ...                ...   
560                41250.00            100             303             6000.0   
361                67500.00            100             301             6000.0   
525               345000.00            100             301             6000.0   
622               105000.00            100             301             6000.0   
723                62727.86            100             301             6000.0   

     col  bi_golongan_debitur  bi_gol_penjamin  saldo_nominatif  \
423    1                  874              875        186667.34   
571    1                  874              875        940000.00   
526    1                  874                0       2000000.00   
413    1                  874              875        744167.00   
67     1                  874                0        875000.00   
..   ...                  ...              ...              ...   
560    1                  874                0        330000.00   
361    1                  874                0        500000.00   
525    1                  874                0       1500000.00   
622    2                  874                0        750000.00   
723    2                  874                0        632728.00   

     tunggakan_pokok  tunggakan_bunga status kredit  
423        186667.34             0.00         MACET  
571        240000.00             0.00         MACET  
526             0.00             0.00        LANCAR  
413        603472.50             0.00         MACET  
67         566176.38         33649.00         MACET  
..               ...              ...           ...  
560         82500.00             0.00         MACET  
361         62500.00          5000.00        LANCAR  
525             0.00             0.00        LANCAR  
622        750000.00         90000.00         MACET  
723        632728.00         57277.06         MACET  

[766 rows x 16 columns]

In [196]:
#mengurutkan berdasarkan beberapa kolom
df.sort_values(by=['jml_pinjaman', 'jml_angsuran_per_bulan'], ascending=[False, True])

nama_nasabah jenis_kelamin  umur  jml_pinjaman  jkw  \
12           x13             L  35.0  2.286550e+08   33   
657         x658             L  40.0  1.000000e+08   20   
430         x431             L  43.0  8.000000e+07   48   
212         x213             L   2.0  4.250000e+07   25   
277         x278             L  40.0  4.000000e+07   40   
..           ...           ...   ...           ...  ...   
669         x670             P  48.0  1.000000e+05   10   
313         x314             P  37.0  9.375000e+04    1   
33           x34             P  58.0  9.000000e+04    5   
18           x19             P  29.0  8.333700e+04    8   
684         x685             P  44.0  8.333333e+04    1   

     jml_angsuran_per_bulan  type_pinjaman  jenis_pinjaman  bi_sektor_ekonomi  \
12               7495303.73            100             301             6000.0   
657                    0.00            100             301             6000.0   
430              2004166.98            100             301             6000.0   
212              2166000.00            100             301             6000.0   
277                    0.00            100             301             6000.0   
..                      ...            ...             ...                ...   
669                11500.00            100             301             6000.0   
313               105000.00            100             301             6000.0   
33                 18000.00            100             301             6000.0   
18                 12812.20            100             301             6000.0   
684                90833.33            100             301             6000.0   

     col  bi_golongan_debitur  bi_gol_penjamin  saldo_nominatif  \
12     1                  874              875     2.094041e+08   
657    2                  874              875     6.200000e+07   
430    1                  874              800     8.000000e+07   
212    1                  874              875     4.150000e+07   
277    1                  874              875     1.000000e+07   
..   ...                  ...              ...              ...   
669    2                  874              800     1.150000e+05   
313    1                  874                0     9.375000e+04   
33     1                  874              875     9.000000e+04   
18     1                  874              875     1.024970e+05   
684    2                  874                0     8.333333e+04   

     tunggakan_pokok  tunggakan_bunga status kredit  
12       91612122.24        7362732.0         MACET  
657      57000000.00       11000000.0         MACET  
430      26666666.56        5400000.0         MACET  
212      26200000.00        6064000.0         MACET  
277             0.00              0.0        LANCAR  
..               ...              ...           ...  
669        115000.00              0.0         MACET  
313         93750.00          11250.0         MACET  
33          36000.00              0.0         MACET  
18         102497.04              0.0         MACET  
684         83333.33           7500.0         MACET  

[766 rows x 16 columns]

In [201]:
#mengubah nama kolom
df = df.rename(columns={
    'nama_nasabah': 'nama',
    'jml_pinjaman': 'jumlah pinjaman',
})

In [204]:
df.drop(['col', 'bi_golongan_debitur'], axis=1)

nama jenis_kelamin  umur  jumlah pinjaman  jkw  jml_angsuran_per_bulan  \
0      x1             P  40.0         345000.0    1               345000.00   
1      x2             L  31.0         350000.0    7                55716.00   
2      x3             L  37.0         649926.0    6               108321.00   
3      x4             P   2.0         459168.0   12                38264.00   
4      x5             P  34.0        3055499.0    8               381937.41   
..    ...           ...   ...              ...  ...                     ...   
761  x762             L  38.0        1000000.0   16                70000.00   
762  x763             P  36.0        1000000.0   12                90833.37   
763  x764             L  28.0        2000000.0   10               260000.00   
764  x765             P  31.0        1312500.0    7               198750.00   
765  x766             P  36.0        2000000.0    4               550000.00   

     type_pinjaman  jenis_pinjaman  bi_sektor_ekonomi  bi_gol_penjamin  \
0              100             301             6000.0              875   
1              100             301             6000.0              875   
2              100             301             6000.0              875   
3              100             301             6000.0              875   
4              100             301             6000.0              875   
..             ...             ...                ...              ...   
761            100             301             6000.0                0   
762            100             301             6000.0                0   
763            100             301             6000.0                0   
764            100             301             6000.0                0   
765            100             301             6000.0                0   

     saldo_nominatif  tunggakan_pokok  tunggakan_bunga status kredit  
0           345000.0        345000.00              0.0         MACET  
1           390000.0        111428.00              0.0         MACET  
2           649926.0        216642.00              0.0         MACET  
3           459168.0        382640.00              0.0         MACET  
4          3055499.0       1527749.48              0.0         MACET  
..               ...              ...              ...           ...  
761         812500.0        812500.00          97500.0         MACET  
762         429000.0        429000.00          45000.0         MACET  
763         600000.0        600000.00         180000.0         MACET  
764        1312500.0       1312500.00          78750.0         MACET  
765        1000000.0       1000000.00         100000.0         MACET  

[766 rows x 14 columns]

In [210]:
df.head(3)#n rows pertama

nama jenis_kelamin  umur  jumlah pinjaman  jkw  jml_angsuran_per_bulan  \
0   x1             P  40.0         345000.0    1                345000.0   
1   x2             L  31.0         350000.0    7                 55716.0   
2   x3             L  37.0         649926.0    6                108321.0   

   type_pinjaman  jenis_pinjaman  bi_sektor_ekonomi  col  bi_golongan_debitur  \
0            100             301             6000.0    1                  874   
1            100             301             6000.0    1                  874   
2            100             301             6000.0    1                  874   

   bi_gol_penjamin  saldo_nominatif  tunggakan_pokok  tunggakan_bunga  \
0              875         345000.0         345000.0              0.0   
1              875         390000.0         111428.0              0.0   
2              875         649926.0         216642.0              0.0   

  status kredit  
0         MACET  
1         MACET  
2         MACET

In [211]:
df.tail(3)#nrows terakhir

nama jenis_kelamin  umur  jumlah pinjaman  jkw  jml_angsuran_per_bulan  \
763  x764             L  28.0        2000000.0   10                260000.0   
764  x765             P  31.0        1312500.0    7                198750.0   
765  x766             P  36.0        2000000.0    4                550000.0   

     type_pinjaman  jenis_pinjaman  bi_sektor_ekonomi  col  \
763            100             301             6000.0    2   
764            100             301             6000.0    2   
765            100             301             6000.0    2   

     bi_golongan_debitur  bi_gol_penjamin  saldo_nominatif  tunggakan_pokok  \
763                  874                0         600000.0         600000.0   
764                  874                0        1312500.0        1312500.0   
765                  874                0        1000000.0        1000000.0   

     tunggakan_bunga status kredit  
763         180000.0         MACET  
764          78750.0         MACET  
765         100000.0         MACET

In [217]:
df.sample(5) #mengambil sample

nama jenis_kelamin  umur  jumlah pinjaman  jkw  jml_angsuran_per_bulan  \
289  x290             L  46.0         264284.0    7                37754.90   
458  x459             L  32.0        1741750.0   20                87087.50   
180  x181             L  48.0        1600000.0   10               160000.00   
589  x590             P  29.0        2500000.0   12               208333.37   
507  x508             P  40.0         500000.0    8                66250.00   

     type_pinjaman  jenis_pinjaman  bi_sektor_ekonomi  col  \
289            100             301             6000.0    1   
458            100             301             6000.0    1   
180            100             301             6000.0    1   
589            100             305             6000.0    1   
507            100             301             6000.0    1   

     bi_golongan_debitur  bi_gol_penjamin  saldo_nominatif  tunggakan_pokok  \
289                  874              875        264284.00         75509.70   
458                  874                0        526750.00             0.00   
180                  874              875       1458651.05        498651.05   
589                  874                0       1033333.34        199999.98   
507                  874                0        437500.00        187500.00   

     tunggakan_bunga status kredit  
289              0.0         MACET  
458              0.0        LANCAR  
180              0.0         MACET  
589              0.0         MACET  
507          11250.0         MACET

In [219]:
df.nlargest(3, 'jumlah pinjaman')

nama jenis_kelamin  umur  jumlah pinjaman  jkw  jml_angsuran_per_bulan  \
12    x13             L  35.0      228655000.0   33              7495303.73   
657  x658             L  40.0      100000000.0   20                    0.00   
430  x431             L  43.0       80000000.0   48              2004166.98   

     type_pinjaman  jenis_pinjaman  bi_sektor_ekonomi  col  \
12             100             301             6000.0    1   
657            100             301             6000.0    2   
430            100             301             6000.0    1   

     bi_golongan_debitur  bi_gol_penjamin  saldo_nominatif  tunggakan_pokok  \
12                   874              875      209404092.0      91612122.24   
657                  874              875       62000000.0      57000000.00   
430                  874              800       80000000.0      26666666.56   

     tunggakan_bunga status kredit  
12         7362732.0         MACET  
657       11000000.0         MACET  
430        5400000.0         MACET

In [220]:
df.nsmallest(3, 'jumlah pinjaman')

nama jenis_kelamin  umur  jumlah pinjaman  jkw  jml_angsuran_per_bulan  \
684  x685             P  44.0         83333.33    1                90833.33   
18    x19             P  29.0         83337.00    8                12812.20   
33    x34             P  58.0         90000.00    5                18000.00   

     type_pinjaman  jenis_pinjaman  bi_sektor_ekonomi  col  \
684            100             301             6000.0    2   
18             100             301             6000.0    1   
33             100             301             6000.0    1   

     bi_golongan_debitur  bi_gol_penjamin  saldo_nominatif  tunggakan_pokok  \
684                  874                0         83333.33         83333.33   
18                   874              875        102497.04        102497.04   
33                   874              875         90000.00         36000.00   

     tunggakan_bunga status kredit  
684           7500.0         MACET  
18               0.0         MACET  
33               0.0         MACET

In [222]:
#filter dataframe
df[df['jenis_kelamin']=='P']

nama jenis_kelamin  umur  jumlah pinjaman  jkw  jml_angsuran_per_bulan  \
0      x1             P  40.0         345000.0    1               345000.00   
3      x4             P   2.0         459168.0   12                38264.00   
4      x5             P  34.0        3055499.0    8               381937.41   
11    x12             P  26.0        4071669.0   20               203583.45   
15    x16             P  39.0        1640000.0   16               102500.00   
..    ...           ...   ...              ...  ...                     ...   
759  x760             P  25.0        1500000.0  100                17250.00   
760  x761             P  24.0        1500000.0   16               105000.00   
762  x763             P  36.0        1000000.0   12                90833.37   
764  x765             P  31.0        1312500.0    7               198750.00   
765  x766             P  36.0        2000000.0    4               550000.00   

     type_pinjaman  jenis_pinjaman  bi_sektor_ekonomi  col  \
0              100             301             6000.0    1   
3              100             301             6000.0    1   
4              100             301             6000.0    1   
11             100             301             6000.0    1   
15             100             301             6000.0    1   
..             ...             ...                ...  ...   
759            100             301             6000.0    2   
760            100             301             6000.0    2   
762            100             301             6000.0    2   
764            100             301             6000.0    2   
765            100             301             6000.0    2   

     bi_golongan_debitur  bi_gol_penjamin  saldo_nominatif  tunggakan_pokok  \
0                    874              875         345000.0        345000.00   
3                    874              875         459168.0        382640.00   
4                    874              875        3055499.0       1527749.48   
11                   874              875        3671669.0       1228667.60   
15                   874              875        1600000.0        985000.00   
..                   ...              ...              ...              ...   
759                  874                0        1080000.0       1080000.00   
760                  874                0         700000.0        700000.00   
762                  874                0         429000.0        429000.00   
764                  874                0        1312500.0       1312500.00   
765                  874                0        1000000.0       1000000.00   

     tunggakan_bunga status kredit  
0                0.0         MACET  
3                0.0         MACET  
4                0.0         MACET  
11               0.0         MACET  
15               0.0         MACET  
..               ...           ...  
759         164000.0         MACET  
760          90000.0         MACET  
762          45000.0         MACET  
764          78750.0         MACET  
765         100000.0         MACET  

[462 rows x 16 columns]

In [225]:
df[
    (df['jenis_kelamin']=='P')&
    (df['umur']>40)&
    (df['umur']<50)
]

nama jenis_kelamin  umur  jumlah pinjaman  jkw  jml_angsuran_per_bulan  \
21    x22             P  49.0       4000000.00   24                81944.25   
25    x26             P  42.0        860000.00    8                88607.16   
26    x27             P  49.0        270000.00    6                45000.00   
30    x31             P  42.0        185169.00    8                25021.16   
36    x37             P  43.0      28950000.00  141               299114.98   
..    ...           ...   ...              ...  ...                     ...   
718  x719             P  47.0       1020000.00   10               121325.00   
722  x723             P  45.0        875000.00    7               140000.00   
726  x727             P  48.0        521000.00    6                94333.35   
728  x729             P  47.0        347000.00    7                55571.48   
729  x730             P  45.0        574166.68    7                89523.85   

     type_pinjaman  jenis_pinjaman  bi_sektor_ekonomi  col  \
21             100             301             6000.0    1   
25             100             301             6000.0    1   
26             100             301             6000.0    1   
30             100             301             6000.0    1   
36             100             301             6000.0    1   
..             ...             ...                ...  ...   
718            100             301             6000.0    2   
722            100             301             6000.0    2   
726            100             301             6000.0    2   
728            100             301             6000.0    2   
729            100             301             6000.0    2   

     bi_golongan_debitur  bi_gol_penjamin  saldo_nominatif  tunggakan_pokok  \
21                   874              875        742662.00             0.00   
25                   874              875        708857.00        708857.00   
26                   874              875        270000.00         90000.00   
30                   874              875        200169.00        200169.00   
36                   874              875      27399322.00             0.00   
..                   ...              ...              ...              ...   
718                  874              875        673000.00        673000.00   
722                  874                0        875000.00        875000.00   
726                  874                0        481000.00        481000.00   
728                  874                0        347000.00        347000.00   
729                  874                0        481666.68        481666.68   

     tunggakan_bunga status kredit  
21               0.0        LANCAR  
25               0.0         MACET  
26               0.0         MACET  
30               0.0         MACET  
36               0.0        LANCAR  
..               ...           ...  
718              0.0         MACET  
722         105000.0         MACET  
726          45000.0         MACET  
728          42000.0         MACET  
729          45000.0         MACET  

[139 rows x 16 columns]

In [228]:
type(df)

pandas.core.frame.DataFrame

In [230]:
#ambil 1 atau beberapa kolom

In [231]:
df['nama']

0        x1
1        x2
2        x3
3        x4
4        x5
       ... 
761    x762
762    x763
763    x764
764    x765
765    x766
Name: nama, Length: 766, dtype: object

In [232]:
df[['nama', 'umur']]

nama  umur
0      x1  40.0
1      x2  31.0
2      x3  37.0
3      x4   2.0
4      x5  34.0
..    ...   ...
761  x762  38.0
762  x763  36.0
763  x764  28.0
764  x765  31.0
765  x766  36.0

[766 rows x 2 columns]

In [238]:
#slice baris
df.iloc[100:110]

nama jenis_kelamin  umur  jumlah pinjaman  jkw  jml_angsuran_per_bulan  \
100  x101             P  40.0        1500000.0   20                86250.00   
101  x102             P  44.0        2000000.0   16               140000.00   
102  x103             L  38.0        1000000.0   12                90833.37   
103  x104             P  40.0        1000000.0   12                90833.37   
104  x105             L  35.0        4000000.0  120                39333.73   
105  x106             L  28.0        2000000.0   20               115000.00   
106  x107             P  48.0        2500000.0   24               122916.82   
107  x108             P  36.0        4000000.0   24               196666.82   
108  x109             L  34.0        1500000.0   20                86250.00   
109  x110             L  41.0        4000000.0   24               196666.82   

     type_pinjaman  jenis_pinjaman  bi_sektor_ekonomi  col  \
100            100             301             6000.0    1   
101            100             301             6000.0    1   
102            100             301             6000.0    1   
103            100             301             6000.0    1   
104            100             301             6000.0    1   
105            100             301             6000.0    1   
106            100             301             6000.0    1   
107            100             301             6000.0    1   
108            100             301             6000.0    1   
109            100             301             6000.0    1   

     bi_golongan_debitur  bi_gol_penjamin  saldo_nominatif  tunggakan_pokok  \
100                  874                0        750000.00             0.00   
101                  874                0       1244000.00        494000.00   
102                  874                0        250000.03         83333.33   
103                  874                0        666666.68        499999.98   
104                  874                0       2466666.82        166666.65   
105                  874                0       1100000.00        100000.00   
106                  874                0       2500000.00       1041666.60   
107                  874                0       2833333.38        499999.98   
108                  874                0        900000.00         75000.00   
109                  874                0       2500000.06             0.00   

     tunggakan_bunga status kredit  
100             0.00        LANCAR  
101         60000.00         MACET  
102          7500.00        LANCAR  
103         58333.32         MACET  
104         30000.00        LANCAR  
105         15000.00        LANCAR  
106        187500.00         MACET  
107         90000.00         MACET  
108         11250.00        LANCAR  
109             0.00        LANCAR

In [239]:
#menghitung jumlah values
df['jenis_kelamin'].value_counts()

jenis_kelamin
P    462
L    304
Name: count, dtype: int64

In [240]:
df1 = pd.DataFrame({'kolom_1': [1, 2, 3, 4], 'kolom_2': ['a', 'b', 'c', 'a']})
df2 = pd.DataFrame({'kolom_1': [4, 5, 6, 7], 'kolom_2': ['a', 'a', 'c', 'd'], 'kolom_3': [11, 22, 33, 44]})

In [241]:
df1

kolom_1 kolom_2
0        1       a
1        2       b
2        3       c
3        4       a

In [242]:
df2

kolom_1 kolom_2  kolom_3
0        4       a       11
1        5       a       22
2        6       c       33
3        7       d       44

In [244]:
#menggabungkan beberapa dataframe
pd.concat([df1, df2], axis=0)

kolom_1 kolom_2  kolom_3
0        1       a      NaN
1        2       b      NaN
2        3       c      NaN
3        4       a      NaN
0        4       a     11.0
1        5       a     22.0
2        6       c     33.0
3        7       d     44.0

In [245]:
pd.concat([df1, df2], axis=1)

kolom_1 kolom_2  kolom_1 kolom_2  kolom_3
0        1       a        4       a       11
1        2       b        5       a       22
2        3       c        6       c       33
3        4       a        7       d       44

In [246]:
pd.merge(df1, df2)

kolom_1 kolom_2  kolom_3
0        4       a       11

In [247]:
pd.merge(df1, df2, on='kolom_2')

kolom_1_x kolom_2  kolom_1_y  kolom_3
0          1       a          4       11
1          1       a          5       22
2          4       a          4       11
3          4       a          5       22
4          3       c          6       33

In [248]:
pd.merge(df1, df2, on=['kolom_1', 'kolom_2'])

kolom_1 kolom_2  kolom_3
0        4       a       11

In [250]:
df1

kolom_1 kolom_2
0        1       a
1        2       b
2        3       c
3        4       a

In [249]:
pd.merge(df1, df2, on=['kolom_1', 'kolom_2'], how='left')

kolom_1 kolom_2  kolom_3
0        1       a      NaN
1        2       b      NaN
2        3       c      NaN
3        4       a     11.0

In [252]:
df2

kolom_1 kolom_2  kolom_3
0        4       a       11
1        5       a       22
2        6       c       33
3        7       d       44

In [251]:
pd.merge(df1, df2, on=['kolom_1', 'kolom_2'], how='right')

kolom_1 kolom_2  kolom_3
0        4       a       11
1        5       a       22
2        6       c       33
3        7       d       44

In [253]:
pd.merge(df1, df2, on=['kolom_1', 'kolom_2'], how='outer')

kolom_1 kolom_2  kolom_3
0        1       a      NaN
1        2       b      NaN
2        3       c      NaN
3        4       a     11.0
4        5       a     22.0
5        6       c     33.0
6        7       d     44.0

In [256]:
pd.merge(df1, df2, on=['kolom_1', 'kolom_2'], how='inner')

kolom_1 kolom_2  kolom_3
0        4       a       11

## data analysis

In [257]:
df.describe()

umur  jumlah pinjaman         jkw  jml_angsuran_per_bulan  \
count   765.000000     7.660000e+02  766.000000            7.660000e+02   
mean     29.160784     2.712483e+06   18.960836            2.333917e+05   
std     263.165564     9.995602e+06   32.076029            5.489682e+05   
min   -7162.000000     8.333333e+04    1.000000            0.000000e+00   
25%      32.000000     8.489286e+05    8.000000            6.750000e+04   
50%      38.000000     1.500000e+06   12.000000            1.050000e+05   
75%      43.000000     2.000000e+06   20.000000            2.333334e+05   
max    1043.000000     2.286550e+08  679.000000            1.035000e+07   

       type_pinjaman  jenis_pinjaman  bi_sektor_ekonomi         col  \
count          766.0      766.000000         765.000000  766.000000   
mean           100.0      301.197128        6013.045752    1.216710   
std              0.0        0.822267         216.196305    0.412273   
min            100.0      301.000000        6000.000000    1.000000   
25%            100.0      301.000000        6000.000000    1.000000   
50%            100.0      301.000000        6000.000000    1.000000   
75%            100.0      301.000000        6000.000000    1.000000   
max            100.0      305.000000        9990.000000    2.000000   

       bi_golongan_debitur  bi_gol_penjamin  saldo_nominatif  tunggakan_pokok  \
count           766.000000       766.000000     7.660000e+02     7.660000e+02   
mean            873.968668       281.300261     2.007386e+06     7.900853e+05   
std               1.460257       408.099019     8.711282e+06     4.139217e+06   
min             834.000000         0.000000    -4.000000e+06     0.000000e+00   
25%             874.000000         0.000000     5.337500e+05     9.885424e+04   
50%             874.000000         0.000000     9.462828e+05     3.391669e+05   
75%             874.000000       875.000000     1.639582e+06     7.500000e+05   
max             876.000000       875.000000     2.094041e+08     9.161212e+07   

       tunggakan_bunga  
count     7.660000e+02  
mean      8.771708e+04  
std       5.682318e+05  
min       0.000000e+00  
25%       0.000000e+00  
50%       0.000000e+00  
75%       5.814889e+04  
max       1.100000e+07

In [258]:
df['status kredit'].unique()

array(['MACET', 'LANCAR'], dtype=object)

In [259]:
df['umur'].unique()

array([ 4.000e+01,  3.100e+01,  3.700e+01,  2.000e+00,  3.400e+01,
        4.900e+01,  2.700e+01,  4.200e+01,  2.600e+01,  3.500e+01,
        5.500e+01,  3.800e+01,  3.900e+01,  4.100e+01,  2.900e+01,
        5.000e+01,  3.600e+01,  5.700e+01,  5.800e+01,  4.300e+01,
        4.400e+01,  5.200e+01,  4.600e+01,  2.800e+01,  4.700e+01,
        3.200e+01,  5.600e+01,  4.800e+01,  4.500e+01,  3.000e+01,
        6.700e+01,  2.500e+01,  2.100e+01,  3.300e+01,  2.300e+01,
        1.900e+01,  3.000e+00,  5.300e+01,  5.100e+01,  0.000e+00,
        5.400e+01,  6.100e+01, -4.200e+01,  1.000e+00,  2.400e+01,
       -4.800e+01,  6.800e+01,  1.043e+03,  6.000e+01, -4.900e+01,
        7.600e+01,  2.200e+01,  8.000e+01, -7.162e+03,        nan,
       -4.700e+01,  6.500e+01, -4.400e+01,  6.400e+01])

In [260]:
df['umur'].sum()

22308.0

In [261]:
df['umur'].mean()

29.16078431372549

In [262]:
df['umur'].median()

38.0

In [263]:
df['umur'].mode()

0    40.0
Name: umur, dtype: float64

In [264]:
df['umur'].min()

-7162.0

In [265]:
df['umur'].max()

1043.0

In [266]:
df['umur'].std()

263.16556417381685

In [267]:
df['umur'].var()

69256.11416692332

In [272]:
#mengaplikasikan fungsi ke suatu kolom

In [269]:
def tambahkan_umur_2_tahun(umur):
    return umur+2
df['umur_plus_tahun'] = df['umur'].map(tambahkan_umur_2_tahun)

In [270]:
df[['umur', 'umur_plus_tahun']]

umur  umur_plus_tahun
0    40.0             42.0
1    31.0             33.0
2    37.0             39.0
3     2.0              4.0
4    34.0             36.0
..    ...              ...
761  38.0             40.0
762  36.0             38.0
763  28.0             30.0
764  31.0             33.0
765  36.0             38.0

[766 rows x 2 columns]

In [271]:
df['umur_plus_n_tahun'] = df['umur'].map(lambda umur: umur+3)

In [273]:
df[['umur', 'umur_plus_tahun', 'umur_plus_n_tahun']]

umur  umur_plus_tahun  umur_plus_n_tahun
0    40.0             42.0               43.0
1    31.0             33.0               34.0
2    37.0             39.0               40.0
3     2.0              4.0                5.0
4    34.0             36.0               37.0
..    ...              ...                ...
761  38.0             40.0               41.0
762  36.0             38.0               39.0
763  28.0             30.0               31.0
764  31.0             33.0               34.0
765  36.0             38.0               39.0

[766 rows x 3 columns]

In [274]:
df.isna().sum()

nama                      0
jenis_kelamin             0
umur                      1
jumlah pinjaman           0
jkw                       0
jml_angsuran_per_bulan    0
type_pinjaman             0
jenis_pinjaman            0
bi_sektor_ekonomi         1
col                       0
bi_golongan_debitur       0
bi_gol_penjamin           0
saldo_nominatif           0
tunggakan_pokok           0
tunggakan_bunga           0
status kredit             0
umur_plus_tahun           1
umur_plus_n_tahun         1
dtype: int64

In [276]:
df3 = pd.DataFrame({'kolom_1': [1, 2, np.nan, np.nan, 1], 'kolom_2': ['a', 'b', np.nan, 'd', 'a']})

In [278]:
df3

kolom_1 kolom_2
0      1.0       a
1      2.0       b
2      NaN     NaN
3      NaN       d
4      1.0       a

In [279]:
df3.dropna()

kolom_1 kolom_2
0      1.0       a
1      2.0       b
4      1.0       a

In [283]:
df3.dropna(subset=['kolom_2'])

kolom_1 kolom_2
0      1.0       a
1      2.0       b
3      NaN       d
4      1.0       a

In [282]:
df3.dropna(subset=['kolom_1', 'kolom_2'], how='all')

kolom_1 kolom_2
0      1.0       a
1      2.0       b
3      NaN       d
4      1.0       a

In [284]:
df3.dropna(subset=['kolom_1', 'kolom_2'], how='any')

kolom_1 kolom_2
0      1.0       a
1      2.0       b
4      1.0       a

In [285]:
df3

kolom_1 kolom_2
0      1.0       a
1      2.0       b
2      NaN     NaN
3      NaN       d
4      1.0       a

In [286]:
df3.drop_duplicates()

kolom_1 kolom_2
0      1.0       a
1      2.0       b
2      NaN     NaN
3      NaN       d

In [287]:
df3.drop_duplicates(subset=['kolom_1'])

kolom_1 kolom_2
0      1.0       a
1      2.0       b
2      NaN     NaN

## Exercise

1. Load data **data_for_pandas_exercise.xlsx** menjadi DataFrame.
2. Tampilkan 3 baris terakhir dari DataFrame.
3. Isi nilai yang hilang/missing values dalam kolom **Umur** dengan median umur.
4. Tampilkan statistik ringkasan untuk kolom **Umur**.
5. Pilih dan tampilkan hanya baris-baris di mana **Umur** kurang dari 30.
6. Pilih dan tampilkan hanya baris-baris di mana **Nama** berwalan huruf P atau Q dan **Umur** dari 20 - 30 tahun
7. Hitung jumlah kemunculan masing-masing nilai unik dalam kolom **Kota**.
8. Tambahkan kolom baru bernama **Jenis Kelamin** dengan nilai acak "Laki-laki" dan "Perempuan".
9. Ganti nama kolom **Kota** menjadi **Lokasi**.
10. Urutkan DataFrame berdasarkan **Umur** secara menaik.
11. Ganti semua nilai "New York" dalam kolom **Lokasi** dengan "NYC".
12. Kelompokkan DataFrame berdasarkan **Lokasi** dan hitung median **Umur** di setiap kelompok. (hint: pelajari groupby dan agg/aggreate)
13. Buat DataFrame baru hanya dengan baris-baris di mana **Umur** ganjil.
14. Simpan DataFrame yang sudah dimodifikasi menjadi file CSV baru.
15. Terapkan fungsi yang mengonversi nama-nama dalam kolom **Nama** menjadi huruf kecil.
16. Hitung persentil ke-25 dari kolom **Umur**.
17. Hitung dan tampilkan rata-rata umur untuk setiap kombinasi unik **Lokasi** dan **Jenis Kelamin**. (hint: pelajari groupby dan agg/aggreate)
18. Hapus baris-baris duplikat berdasarkan kolom **Lokasi**.
19. Gunakan fungsi `apply` untuk mengubah semua nilai **Umur** menjadi string.
20. Hitung dan tampilkan usia maksimum untuk setiap **Lokasi**.
21. Ganti semua kemunculan "Chicago" dalam kolom Lokasi dengan "CHI".
22. Hitung persentase masing-masing nilai unik dalam kolom Lokasi.